Helper = require('hubot-test-helper')
co = require('co')
expect = require('chai').expect

helper = new Helper('../scripts/test.coffee')

describe 'test2', ->
  beforeEach ->
    @room = helper.createRoom()
    # return
  afterEach ->
    @room.destroy()
    # return
  context 'user says test to hubot', ->
    beforeEach ->
      co (->
        yield @room.user.say 'alice', '@hubot test'
        yield @room.user.say 'bob', '@hubot test'
        # return
      ).bind(this)
    it 'should reply to user', ->
      expect(@room.messages).to.eql [
        [
          'alice'
          '@hubot test'
        ]
        [
          'hubot'
          'TOST'
        ]
        [
          'bob'
          '@hubot test'
        ]
        [
          'hubot'
          'TOST'
        ]
      ]
    #   return
    # return
#   return

# ---
# generated by js2coffee 2.2.0